export interface EnvironmentRaw extends Record<string, unknown> {
  ACADEMY_JS_AUTH_SERVICE_API_KEY: string;
  ACADEMY_JS_AUTH_SERVICE_CORS_ORIGINS: string[];
  ACADEMY_JS_AUTH_SERVICE_DATABASE_CONNECTION_STRING: string;
  ACADEMY_JS_AUTH_SERVICE_HOST: string;
  ACADEMY_JS_AUTH_SERVICE_MAIL_DEFAULT_ADDRESS: string;
  ACADEMY_JS_AUTH_SERVICE_MAIL_HOST: string;
  ACADEMY_JS_AUTH_SERVICE_MAIL_PASSWORD: string;
  ACADEMY_JS_AUTH_SERVICE_MAIL_PORT: number;
  ACADEMY_JS_AUTH_SERVICE_MAIL_USE_TLS: boolean;
  ACADEMY_JS_AUTH_SERVICE_MAIL_USER: string;
  ACADEMY_JS_AUTH_SERVICE_PORT: number;
}
