packages:
  - packages/backend/auth/*
  - packages/backend/libraries/*
  - packages/backend/tools/*
  - packages/foundation/tools/*

ignoredBuiltDependencies:
  - better-sqlite3

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
