packages:
  - packages/backend/apps/auth/*
  - packages/backend/apps/mail/*
  - packages/backend/libraries/*
  - packages/backend/tools/*
  - packages/foundation/tools/*

ignoredBuiltDependencies:

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
