packages:
  - packages/backend/apps/auth/*
  - packages/backend/apps/mail/*
  - packages/backend/libraries/*
  - packages/backend/tools/*
  - packages/foundation/tools/*

ignoredBuiltDependencies:
  - better-sqlite3
  - oxc-resolver

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
